### ISSUE TITLE
ETL website code

### ISSUE THREAD

**Issue by amanotaiga** [amanotaiga/Tensorflow_CNN#1]
```
id_dataset = 0
new_img = Image.new('L', (128*32, 128*30))
with open(filename, 'r') as f:
    f.seek(id_dataset * 956 * sz_record)
    for i in range(956):
        r = read_record_ETL8G(f)        
        new_img.paste(r[-1], (128*(i%32), 128*(i/32)))
iE = Image.eval(r[-1], lambda x: 255-x*16)
fn = 'ETL8G_ds{:03d}.png'.format(id_dataset)
iE.save(fn, 'PNG')
```

Sample code says that **The first 956 records of the first data set are shown by above codes.**
But when I tried it ,I could only have last png,and I revised it to below codes it could have all png.

```
id_dataset = 0
new_img = Image.new('L', (128*32, 128*30))
with open(filename, 'r') as f:
    f.seek(id_dataset * 956 * sz_record)
    for i in range(956):
        r = read_record_ETL8G(f)        
        new_img.paste(r[-1], (128*(i%32), 128*(i/32)))
        iE = Image.eval(r[-1], lambda x: 255-x*16)
        fn = 'ETL8G_ds{:03d}.png'.format(i)
        iE.save('ETL8G_01_data/'+fn, 'PNG')
```

I have 2 questions about this code

1.Why `seek()` only have to be used once?And why it's written as   `f.seek(id_dataset * 956 * sz_record)`,
I thought that this would jump to the end immediately(when `dataset`!=0).
Though I've check the definition of `seek()`,I don't understand why should be used in here.
Though it is used to update the position,but in the loop,
it only use `read()` to update the position.

2.Why I can't get all png by the sample code,I thought that sample code wanted to stick all imgs and make a big png consists all of the imgs.

**Comment by caranha** [comment]
Hello Huang, just a quick comment to mention that I saw your e-mail. I will answer it when I have more time tomorrow.

Cheers,
