### ISSUE TITLE
Create Scripts to transform data sets into images

### ISSUE THREAD

**Issue by caranha** [amanotaiga/Tensorflow_CNN#4]
I suggest that you create one (or more) scripts that transform a data set into a series of images. This would make it much easier for you and other people to work with the data set in the future.

The idea would be something like

   unpack.py ETL1

   ... Generates a directory with one .png file for each character, with the label (index) in the file name.
   ... e.g.: L1_000.png L1_001.png L2_000.png, etc.

**Comment by amanotaiga** [comment]
ok first completed unpack_ETL1.py. Would support other datasets
