### ISSUE TITLE
Task: Visualization of Training Results

### ISSUE THREAD

**Issue by caranha** [amanotaiga/Tensorflow_CNN#6]
- [x] Generate Confusion Matrix from training results from issue #5 
- [x] Generate a "summary" of Confusion matrix to identify problem classes
- [x] Generate training and cost graphs

**Comment by amanotaiga** [comment]
# have been solved

could generate confusion matrix but have trouble creating summary of it.

[stackoverflow-How to apply the output of numpy.argpartition for 2-D Arrays?](http://stackoverflow.com/questions/26322232/how-to-apply-the-output-of-numpy-argpartition-for-2-d-arrays)
It says that below could get the top 10 smallest,

```
top = np.argpartition(myBigArray, num, axis=1)[:, :10]
myBigArray[np.arange(myBigArray.shape[0])[:, None], top]
```

and another [How to get indices of N maximum values in a numpy array?](http://stackoverflow.com/questions/6910641/how-to-get-indices-of-n-maximum-values-in-a-numpy-array) says that below could get the top 4 largest.

```
>>> a
array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])
>>> ind = np.argpartition(a, -4)[-4:]
>>> ind
array([1, 5, 8, 0])
```

but when I try the first code and change num to -3(top 3 largest),
it would show 69(72-3)elements like below.It should show indexs of top 3 largest values.
![summary of confusion](https://cloud.githubusercontent.com/assets/18046528/20246260/9e9996e4-a9f6-11e6-849e-14ce8531f0ab.jpg)

**Comment by caranha** [comment]
How about trying a naive approach?

Loop over the rows of the confusion matrix, and for each row loop over the
columns, keeping track of the index and value top three columns?
