### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by caranha** [amanotaiga/Tensorflow_CNN#8]
Create a script that executes cross validation of a classification system.

An n-fold cross validation procedure divides the training data in n groups, and repeat the training procedure n times. Each time i, group i is used as the test data, and all other groups are used as the training data. 

The final result of the cross-validation script is the average and standard error for the final values of the train error and test error obtained over n repetitions.

**Comment by amanotaiga** [comment]
Finished
